"""
:
@author: lingzhi
* @date 2022/4/15 17:41
"""
#----------------------------------------------------------------------
# This file was generated by e:/Sketch_wxpython/encode_img.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

cursor_eraser = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAERSURBVDhPY2RgYGCMj4/ntzC1t/r4'
    b'/r00kE8Q8HHz3li5cenpgwcP/mABaQ7yiyi3sjFPZWVj5YKqwQt+/fj1kYWdvRFowCzmjNR8'
    b'J3dPlxY+AV5hVlYWVmIwByc7Dx+fgBwrG+dOJpCz2diJsxkZiIkLK/Ky8xgygTj//4PFSAP/'
    b'/zP++fObFWwAJYB6BjAygmKUdAA34D8wIMgxA8UL5ATmIApEUgHQt3+5uXi+MvHx894ApW2o'
    b'ONHg0YMnl67fu3WG+cu3T6/YmDg/8vEJyrEys3L9+vXr96+fv3/hwT9u37h36tDhwxO7e5pP'
    b'wyKOqTinWp6Lm9MIlDyhYlgBHx/P13tPnp6ZPXvCCwYGhv8Ag0N4n92GZdgAAAAASUVORK5C'
    b'YII=')

#----------------------------------------------------------------------
default_file = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAItJ'
    b'REFUOI1jYKAQMMIYBw8erGVhYWnCpfDv379rr1+/Hpmenv4bpwEMDAwM9vb2zeiaYYb/+/dv'
    b'zbVr16KQDWEixblMTEwhWlpay+rr61nIMgBmiKOjYz6Mz4JPMQxAvdXMwADxDiMjIxfZLsBw'
    b'0agBw8EAlITEwsLSdPToUZwZCgb+/PlTR6nFcAAA06IsC2ykkLMAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
default_folder = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAKdJ'
    b'REFUOI1jYBhowEiMom09HoYcrBxMyGK/fv/56lGy5QYLIc27Jvg4s7Gy7/n77+8VRgbGn1Bh'
    b'HlY21g8MDAwWcAN29PhosLGycGOYwMTY9O/fv6c/f/xJ4mBj+cfAwMDw7/9/A0YmplQGBgYG'
    b'uAGsbKwLmJiZzHG5hIuL/RTcTAYGhr9//52EsSkCowYMBgPg6eD3r98JjNgSEg7w+/efr5Ra'
    b'Th0AAD4XK99ShLYvAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
default_folder_opened = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAATJJ'
    b'REFUOI3FkrtKA2EQhb//stkLEpE8gJWVhQrp7FSw11Kwk3QiRl/AB5CU6iskYiWCWKbWKiJ2'
    b'YiHayGpSJMvObxGzhBRJthBPN4c53zDDwH9LTdPUqh+u+GFBD3vtXu97eev02U4MXx2v+753'
    b'l4o8GBAAgbnQ816AtQzQqh8s+mEQjAJSx4lI+mRQewNPYEPBJkAG8EK/keKsQcXDAKMAVAc4'
    b'H3gKNwu8Atj7xv5CMYiK4iSQ1NWMNc1xK7W7Sbdg7LwxVAFsVAgqaF3VaLShNukmke8lkqY7'
    b'0L+pduKuJ4WGpbX2BFnK6s573BSReFxoVEbZcgYoVy4SBbd5AEpTds71AQBJKjnXMCWtmMkA'
    b'n/HXjYi4PBCULsHvH6zunn08Xh5tW6OiafM9JW+5Bv6ZfgA9hF6J2DJlnwAAAABJRU5ErkJg'
    b'gg==')

#----------------------------------------------------------------------
file_type_audio = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAQ9J'
    b'REFUOI3N0D0vg2EUxvHf87SEDl1MTQiJ14hVxEBXi8Gq8Q3EQFJtlMFLE4tvIbELo5fVxGKo'
    b'2NgkEomkkaaPoWik9dKJa7rvc53zP7kO/1y5CQpn33WEX1v5edrOCLo/1zNJ1rI/AAo7tO8T'
    b'djR6qT7CIstDEK8V17KE/bV3NEws3TiYSdI7RfGI9VMSi1h6A8R3v47yrr4M4SbpHqJjzH0T'
    b'oZmeDtHF+AiVG4LBFgHxCBHB+0ysRUDnLB65uCYcICrxccTKav2IRginGwH3B6TuOC8zNYMr'
    b'CJqsCigUieVq3+otWwN1e2WMxCXPo+yVmkWI2M7zskC13Gg/3FHdYK/0i9y5SQonv2j8Q70C'
    b'3BA5LuJnSKoAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
file_type_bat = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAlFJ'
    b'REFUOI2lkstrE1EYxb87dx63SZqkzdSYtFr68EHFItJ24cqO2ICCgoF0GayIiP+C1K0Lly50'
    b'4UZIi7gIhSzaDpOFiwrio9SCTSUUtaS0mekkoenM5NZ73UkLpi14dmfx/Tjn4wD8p9B+o+t6'
    b'2rbtaVVVv1BKxwVB6LNteyGVSpWbAYT9hjGWIoSsO44z4LruJ8bYE1EU245MYBjGXcZYslqt'
    b'3Vz8VoSNsgWtfh9cvtAPHZH2D4qirGualmyawLKsjOu6Q0uFNeDA6iOXBl6f7+/+vvKjBI7j'
    b'jjQajReHVlBV9StCKFraMqH3dOfbBxPpNNrzbnXGO1jdcUEUxcezs7OjTQGe591hjDnhYAD2'
    b'OL+SyWR6I/H4U0mRhRYiA+f8VaFQWGgKwBj3SZK0MniuF36WNs9uu16xXKncJiAAURQTIXQt'
    b'Fovt6bp+8Z9PnJmZiQJAqyzLU57nDVdqO+DzEfARYnLO78myfAohtIIxnrMsqysUCg0nEokc'
    b'APADO8jn828opS9FUXzGGHuOMR6llBoIocmtshWq1Xfb4yciq4FAIFKtVgeSyeTWgR1omjae'
    b'SCTyjLFJ27anTdN8iBDa3SxbwYXPy9Jvzoyl1bUeSmkxGAxG/1Zopvn5+SGM8bvlQlERJXHu'
    b'0f2JG1PZbElmHLW3hVs0TQsLhwHGxsY+WpbV3RVVf21Xa9enstkycB5TZGnRNM0YAIB4GAAA'
    b'IBwOjyKE8OCZnvdug/YTWZrz+/0aIUQGAOeoewAApOt6SNf1q4ZhbACAkMvlTh7n8Fj6A9ed'
    b'+wSGiiqQAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
file_type_binary = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAa1J'
    b'REFUOI2lk89LVGEUhp/v3ts401wdHXNTuRBMWqkwMFhQJjP6F7Rs2U36AbPKbbQQI1eWJZO5'
    b'6y/IRQTj6BTiqBTWYiCYRYTRlCYVImLX77QaGLhfeMGz+s7LOQ/ve+CDY5aqP+YGM69RdKLs'
    b'PeOk1u7Pvd9XxtbXa42y09j4+wfXRstv35v2ZwezN5PxxMJk74Whux9XftR1K6xVr1SYEWG6'
    b'LRkv5FOpU0YHAPf6+lo7E+05rWTnRmnx8VQ6fdaNtozt7v956JUKM88vZ5TT3PYSuGh0cKa5'
    b'PXuo+WRjXQXIra1taqQadZwmgOtvFp4KuP+NcCJiK8uiR2ApTLQA4HPt6ysF/l/fXwSYHhjo'
    b'VooWq8nNmACBG9yvVHbzqdNPqpvbPsCdcrkKjAMSCjDV399huzLRcy45y3dWH6UvdcWikVso'
    b'OemVirePjJDb2NgSUcV6H4vHhlHsWKhuk4MAIJ/KJkB3Wco+DygO/G9KRCPyIRQASGA7W2Lp'
    b'CCDecnFeDqn82q49MAECNxh9V/gCPGvUvOXivGk5AHCikRdzQyPmz9RQIrr1qJnQ9Q8aFYoA'
    b'qydLagAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
file_type_c = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZNJ'
    b'REFUOI2lkL1LW1EYxn/3vVevtgglWAcHtZNQSCjUxSIpDk6KGeQOGkIm/wHr0AoluNgglrQI'
    b'XbtEBQOKUCh0qyB0KIUScBEE4x8gOsSPnHNuh3xebtJCfaaX57zPj+c9cE9ZbV3Ps3HGJuju'
    b'GQXgTl1RLh9x8Pb834DkxiyWbGLbQwHfmFt8s8rtj3UKBV23JbA0/34OsfdCYQARF9tZw33x'
    b'OWA3pqlXD3HkEyI2AFp/BcYoX8fQKosxutY5iZeN1mNOA/B4MIHIQLWuPiF/MAvfVe31Dalc'
    b'FGPi+Pyiy3kKFIMAoUHF+PmWcFU3JY9C7jp0WXO0Yi3zWegP2oSDAMtqmYm0W/47wPeLTYCM'
    b'hzYT70ZIf3zOy8yj9gBtfjdtE2cm0x8A9LkrwE9GIhekPuw2y9Y1nO4h/uwYkSdVhjmlohZx'
    b'uy9RahqRFURcAFRlga3lnSAAYGFjBtveR8Shk7Q+JL80CZjgCQDby1+oqAmMPukQ3uf8MlEP'
    b'hxu0ystGedA7XqtsuFPfKLwuddz/X/0BKIZ6K6fGiJkAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
file_type_cheader = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAANhJ'
    b'REFUOI29krFOAkEQhr+dOwiVobX2Me4FMLHEmHDxESQRGioI1B4Qn0FDca/AM1Bg7E3o1FhR'
    b'cORuls7C9bwTlL/8d/bbf2YW/lxh1Ce865QtF9eRJsa72B/wSxUDGjcnPx0bx7meLLG8ozrD'
    b'kyEip6i+ofrAY9eZzfcJDAEiAzI7Jd1egX3G929pRe2vpX5OsgpJck7cewLgcjCnVn9FJADu'
    b'ixNYu/q8DBAPP8Au8OSsXAvw4kLNGtVqSYDJcsCOjvAP/hvgrlHTEdZsXD8bY2zt0Acd7QD+'
    b'mjna8FJwpAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
file_type_cmake = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAfNJ'
    b'REFUOI210c9rE0EUB/BvZt2ZSSYmZmPaLJiktocYxBLRGiGpNAcvEvGgCOqhoKAoWkit6MWD'
    b'eJIeBPWg/QvEsxcJnrx4KPRiDy3ijyZaLWhiupnsbnYbD1aMFkMj+GB4D968D8M84H9GJjM9'
    b'dhIs3+0O6dYcGDhQ3O8T5/4JyGSmx4LBWCG2haQvAYd6BnQ9XWy3QVzFK4c5v9oTkErdHFWU'
    b'SEFKC001YOmKUjgP5DYNaOHhKctyiJQmmjTUUlWVHAwErm0K0PWJ3JqrFaS00JAWDBoGYwwJ'
    b'r7dwnfMNr9gACLF7yrZd0pAmpLTQ3hltMcYghCAjkchkV4DzC1nH0Y5KaaFer7tnTq++yE4c'
    b'6WOMgTGGIb//2K1IJPtXgNLBSdt2iWzWjCuX5Vw87hn9bBiBn4AQguSi0WLnjPKrHM+qNHVH'
    b'bv/wyXh042PbbBi+is8xpRlKzs97KaWglEJjbFdcVZ8/q1bLvwE+cequk35PzMe3vW7AHloM'
    b'LyRK/SVtobr4uoHau71fQrqfccI59wQ5D84sLT3pAMaza8eXT7TuzSQ9KkJwALR+nNrWav/L'
    b'wdUdD/ZUvs75vs2OVDWaZNv2JSgtPV1ZqXgAAIdj93G2nIdn/U9MAHZHttZzC0AbSC6Lcv5V'
    b'35uHs28v/rmVnuM7BfanEOpdDwYAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
file_type_cpp = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXJJ'
    b'REFUOI3VUksrhGEYPe/zvd+4lKmpKbHwAyyllLCYxiX+wBRKUTTmC4NkISwsJOM2ZmEjl6xm'
    b'Qw19KayMDdmwUspCKVHYvTcLQ8PCl6Wzep7O0+mc0wP8e7D8ZaZmpjQQ9DcAOqCEuH98eT2d'
    b'Ppt++k2Afw7LLYsdnFiKGEoAAvkKEPSzdgA7ngKJ8Gw1J7YBmDch5LCUIuuz7ZBU6tYrAgeA'
    b'QrtgiohIStHtuPF0jssCwErLfITIquvfH4wBQKotEYahnuj+YOSrg1Tr0h2AssuHq+K18zXx'
    b'qZ5sTnQSUR8YKowx21qrrMW5A8OqwJCOZgZ6KXfrB6Cfz5+1l+Wf+BBguCEiX31jbVM+GXPj'
    b'W8qoFQPs9h8MjTvuyB6gZwFzGM0M9H5FSDYvdHGbr2utH402k9qIa2I8pI08ctzRE08HMXdo'
    b'UyqZIqKgxa1V2y48tjifgKFyrwjfHmkpNFdpF/nqlFRaCHERPxq7+Esf/xTv94qGwOyYDewA'
    b'AAAASUVORK5CYII=')

#----------------------------------------------------------------------
file_type_excel = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZ9J'
    b'REFUOI2lkrtqlFEUhb9zmf8fZSIZRpPINKmsUvgGKhIbsfACCjY2voEWCl7QqC+QxkabNCnE'
    b'ws5CCytLSRFQUioiqBkvcWb+c/ayMA4ziUyErObAYq911tps2CXcVuLgo0vzNR/PDXO+CH7f'
    b'zFQ91tzGXy6bVt4cubsYtxrUQnEleE4McyFEasXoaAwALPrdFYAIcGDh5DWCmxXi++raYZcc'
    b'SJCNot2iPjVJ1e0PRJLkvP80MPAh3JeEk3CNEklIBhKdlTWqQ9M4PxLWAdMAHkBmyDJPLz6g'
    b'PbGf5Qt3aJYNzGzHCpsGGZlx4/lDls7f4tnqKz7/XEc5g4Sl1Bu7AzNDEtF5eqmPl0Mpo2yU'
    b'X3rU4o/ya3o3LoERnef2/GXOPL7K6bmjtMoJlNKfZY6BA2jePC5lQ2aw+SobmOHfdihnJum3'
    b'92wTry+8dBGg6navB3OzSaAPnbOushYS+pWIFnCVUbzvjoiz2cYgwTCap+ZeBB+ODTruLfDh'
    b'3/f2cem1237KjXrlQxjbexjbDPo534suPNlRmfrf/vuXcfgNeSyxERzh+jwAAAAASUVORK5C'
    b'YII=')

#----------------------------------------------------------------------
file_type_html = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAddJ'
    b'REFUOI2lkc9qE2EUxX/zJemYNiUuaqogVlsVUfAf+ADRdudS8B30EcSFryBIN+LWjbsihRIt'
    b'3QUXdlcoJdUMqZOaqJlkYjPJzL0uRieNjQvphQ8ul3POPfd8cMyyACqL8+fsqXT1f4hBN5xb'
    b'KO06BsDZ2f36L+D0bHrk5U6lUNWEkwYoVuk518UzxuTNnXuQnUoEMoVhrz/b9D+soqpesUov'
    b'EQBQpQHkU0sPMfPXElJ2Zibpw8omQXkVhcRxImBZ1IGL2v6BNF3C5ScA+AV76ODARwQs2P8z'
    b'M0MH2gBQ7xvWicnxgQwCVIbYUQdQB6DTwsrlmXj6CoDcoROCt8v0Xj8fYsdkQPT+DbK5kZD8'
    b'go05WWDy8QvEa6CiCXbkBEHrAObSjXi7KlrdRpwtpBVnpn4LFU2wIw4yKdMEkE4LgNSDR8jH'
    b'DTKzOTK3FmMBr/E7xDEZBH1xbdvAXoWovIZ15TbpyzfJnj6DeA365RWiLxUQiCLrqIOBHDRt'
    b'pqHbJnz5LB6eXcAvTCB7O/GZokgUY49k4Nbcmoi8ExFJEqxVGHzepudHdL+HdPYHkYRRya25'
    b'tUO/N1rrV8nNXTh/N2WZJcsy91FUVVfCSEqO82m9uIX/N+dY9Qvwveuh5P/WSgAAAABJRU5E'
    b'rkJggg==')

#----------------------------------------------------------------------
file_type_image = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAARtJ'
    b'REFUOI1jYBjygJGBgYFB98z8/+RovmySyMhErGJmBkaGQmljhlgxLRRxog0QYeVkSBDXYYgR'
    b'RzWABZtiFkYmBjdBBYZt7+7BxV7+/saQc3cvw8tfXwkbkC9txBAtpsXw5OdnhktfX8PFD398'
    b'gqEWwwsWvJIMcWLaDCyMTAwdinYMPMysDAwMDAzOAnIM/sIq+A0QZGFnaFO0ZWBkZGRgYGBg'
    b'kGHnZaiWs2QQZ+ViaJC3ZqiUNWeQZefFbUCjvA2DCCsXigIBZoih/CzsDFzMrAydivYMLFAL'
    b'UMLAik+KQYyVk+Ha1zdwyV///zHsfH+fIUJUAy7OxMDA4CGoxLDl3V1UA459esZw7NMzDD8y'
    b'MDAwbHh7B6v4MAEAF0Y70DBaOWIAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
file_type_java = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAb1J'
    b'REFUOI1jYKAH8KyaYYJLjokI/YxsLGzGZBsQUDen5M/vH0dhhpFkQED93I6fv38fY2JhUXar'
    b'mKLCwMDwn2gDAurn9fz7y3CGnY3d8efvX1d3deTcwaYOpwGMjIyKm1qS1zAyMqYy/mf+g0sd'
    b'TgN+ff1R4VU90+rf/39TOTjYwkgyQCa0kHNrd+Ztxr9/r//58Wvn339/TjIwMDC4FU2V9amd'
    b'aYqslhlds3/93DZJITFxTZcgFmZWVsH///9xs7Cxf1M2cxfb0ZN1S8sxKOO7gsHxjxcP/mFg'
    b'wBItDAwMDL61s/yZWdmeMDAwMPz6/ZOF9T+r7vOPD1fxcUkJcLMz229sSlmM0wUMDAwMYvou'
    b'77i4OZwYGBikWJiY2X///nHhQG/Zk19Sqr9OT686i6yWBZsBPDxsooz//pszMPxX+s/A8IGV'
    b'jWOvcdrMe2dnpX9DV4vwQmgoc6CW5+L/DP/O/P7z/xwrO+vnWy/u31TkExdj5eIS/Pfrj+qf'
    b'f/9u/P39n2lnd/oFBgaGf1jDwClvgjgHD5cFMyODCAMLk/ifv/8uMTEx8f///fcZCzOzOAMj'
    b'w8tNzSn7sbmcLAAAc9KYICG1BUEAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
file_type_js = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAUtJ'
    b'REFUOI3lkL8vA2Ecxp/v+/ZyNzRFtVcGMZSGGCwkjVhZGMTEn2AwG6wkrAxsbKSzNEyt/SIS'
    b'TahrJRZSrf64i6pe7n0NVJoQ11V8x+d58vk+eYB/dZRIgHeUtEz98OWuX5bzPV0AUDP1LcvU'
    b'C3Yu4lqmfmAYUFpZ5gUr3vRO+jhfAyEtJXaJKD6gBQZbvs8LoBANAYAQSHXHCvufT0XHDR6L'
    b'pRMhRFnx8T0rFzkrZYIj7b4nYHQadv3ZHnNd95gzNqtqymUlG178HUAfeqlYkQBwfl8vB4af'
    b'lt+ar+MAGpzTaiv6tYFl6utENMHANgTElBDCjsVhWzl9h4D56rWzIgRvAHAI1Pe9AZMuY2wB'
    b'DAZjLCql3AYgnaZzBFBYUbVTVVPSgFSFkJs/Ni9cBaLVbGjp4cIfbtczKfirt8GZWj40l0xC'
    b'9drtj907M7p5vz1CFdcAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
file_type_markdown = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAUNJ'
    b'REFUOI3Vjz9LQlEYxp9zr1dDcBGhCGppj+RmLUGfoCCiPoEoLRJFH+MWuoTV1NgNG1pqlYZO'
    b'cdJqjIaCRCRsEP+k55y3QST7h9hUz/Y+8Hve5wH+vRgArC9N27+BHZcLAwCIUbRfuMMY7YsK'
    b'jsuvAdi1VrPmuFw8gt8qkuHXuqw6LheVknwAYD+XiveOywWICu8BAGK27TVMlvZ7rZPYrB0a'
    b'QSRleaxdzwBmAMAKYtQwWToQCA11N/F80y4YGDQ5gGGtdbPXFOOzoZTaIMCvtYoDqANAYmEi'
    b'4rPMLAD4/OZ5Yi48/mMAEYpVepncOhT7HS91lL9UUi5qrStStuZTx7mbLwE7QjS1onhDyXza'
    b'vXtqh9GqbOAMAJKZq9MylceSmVy2+yEDgLXlqW1GbK/X3g9NGUU3Dy5WDADoF/4t80f1Bkyi'
    b'hwkd46ynAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
file_type_matlab = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAdBJ'
    b'REFUOI29ks9L02Ecx1/P93m+3xVLnJBKxKAfVIiWkhGNlrXVxT9ABnnrUOEhClGrHWJZuFYQ'
    b'LDtIFw+dImhQEV36hQleWokxF6YZVJIxioXS+n6fbwfZiGgsPfS+fj6vF++HzwP/K/19l9tW'
    b'DCe7zsY+dR3Qw+cH+v6cGZXgbdcyu5oXp86sNrVoJbs8QUM83diSy97b4nwwpRJsdd75bl7s'
    b'Cf2ToOn6ZKJQXfXi8MzdemUJDCVQpiH8eiFWUdA49GbYm5vtaR9PWTu+vUZaAqkECNi8OBu4'
    b'1YEs7qrfwWBycq9lGseqJ550el/ep92nUF6BNJcauBp8dl4V/L3dkEiUBKHBzBFpWieB7QD5'
    b'poOE5zNs+jKCrLGQUiAMcDVoG9YufD4OJEpP+PGz8NzR2i42Cb1KEZx+hrIEyhQYpsCQoLWL'
    b'tl025qY2RCNRf0kweqo5+/hReo/j2Jdq56cnQunbLoDyGEjPUn0EjImGtw88gaGPsu77OvIX'
    b'yp4vdjR+ZTzY6r6PBNyvJ9rcwrmw+3Cg905xvh/UYKT7BoAoJ0l1dM7tXjVTX1VrMla3c+TQ'
    b'6av7/rZX9h/M1ayP41GMrml5Wg6umGS0P7wicDn5BU/LklEjUz/RAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
file_type_onenote = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAbtJ'
    b'REFUOI2lk09I02Ecxj/v++63TWZMBWGgoP1zxF6XmKIonkRiYYcg6BIdPFlkehDEg52kS93S'
    b'YNBF6lIHQShTUBcEojCUDFPIQ2VTKrUCnc1tPzsYv6abOfA5ve/Dl+f9PPB94ZgSB42buttv'
    b'OJQWSJ+QaCVF0e+deGv/7L3woQEd1XefiF20VKoi01AymXyhFCt7Z+YSSXO1b7Z3EMAGoKS6'
    b'/j/M1r4bzd6a09Y9/GoO79Cp6bZgS60tm55vnk3zLrQAQP3VaqoCftYjPzRBkKmDl+804S48'
    b'gT3H4EpnIJts9hFcCPhx5jp52T+Gt/Yf8rm6s5ToIgDyPG4G7w/zaT4STQuI/tom3+PGc7Jw'
    b'3ysLkx9YXfpqVbDn2NENZQ4GDlQAGAmGuHSr8Wh2Icw0AoDP8xE2f26RW+A6tEI8FufL4kos'
    b'LWD08WsAhh9NUHmx3PK/L6+jbHuwrjwXhsPgTGWpMy3g7dh7AL59XGMkGLL8teUNErEEACW6'
    b'GADT3JUZK2RSw7UaUhcpFg1HF6eWHsDfVW6v6nkqEb5sVhlgJ26OP5zpfW4FpOp2Rdd5qQyf'
    b'RGik8B31mY6tP4WWiK+KJQoOAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
file_type_pdf = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAdpJ'
    b'REFUOI2lkE9rE1EUxX/vT4aUBO0IboJYF9XFLFrQBIOCShTsF3BTyLoKQuyX8Au466JbwYVr'
    b'cREICCY2KlTFYGywdZdJVoqvyWTec1FnsDEtBQ/cxT0cftx74D8lpo12u/1Aa31t2o+iaFAq'
    b'ldZnAj6vrt4/1e0+RgjwvDnredkY2AdGzmGAcRBYr1r92mq1lmq12igBaADb7188s7XlT4RA'
    b'bW4SxTG/9vbIzM8z2Ngg7HQYZ7PyxsLCJefcF+AC4FLAD+AbYJwj12jwczDAW1xk0G7T63QY'
    b'A9Y5jDEUCoXzzWbzbblcvpwChr7/5vvycnckpYt3d8+6fN7f39lhIiXcuY3NePhBgFIKAN/3'
    b'g3q9frNSqTT+KbHX6z3xff+htRZrLaL1iihYwmXnSLw4jhkOh3eLxeJLPQ1QSqG1TsPCGDCG'
    b'OJdHCIEQAudcmpfTACklWut0ZDTC+/j+kKe1PhoghEAphVIKCaiMhxiPUIN+6iddpCXOusBa'
    b'C8+f4grnEDqDfN2A7XfY0z5ubf1oQHKF+LSNyuXh+q2DPq5cxd6rgrXoyeR4gK2/wHU76LVH'
    b'B/ufQpP5WzMBsrIClZVDb0kpTwYIw/CZMaY5C5woiiIRhuGH4zIn1m+I9dG2heI4vAAAAABJ'
    b'RU5ErkJggg==')

#----------------------------------------------------------------------
file_type_powerpoint = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAfRJ'
    b'REFUOI2lk09IVFEUxn/vvvds8MmMM85gA1aUswgXFtkYQe6iPwgt2hS0CxGi9pK0KIjaVBDU'
    b'SmrRKnA3RJsiiCgkLKS0FhUTmGKjk9FAjjPvndNCZ1CfQ1BndeH7vt/9uJwL/zlWI2H6TG+H'
    b'67Xsb0m2JbxY6wLV5TfWpQczfwV8HexJe05ixBjTD9CcSL2NxGP7ABDJsbA4aF1/+L3mN2vD'
    b'8+eO9HhOYqoWBhANEnWDMSdIxqf06sDedQ1eHe+86IvJ/PA55RjjAagqPtDdtfvnrp3bWtfV'
    b'lOAdY8WsNTpaMQC2ca5tsa2zW128pAlos3yS+LRrlY+zhWjogYzdTTZ+AcABUBEQZc+9J/ya'
    b'HAcRvtwYQlUxlmVCgJVb+4BbBkADQUWoLM6Tv3OZ5s4usF0kENBN46BWdn0DVdx4ih0DQ+Tv'
    b'XsEvL6GiFGbmmHzxMpwXaQoBqsUCn28OI6qIKCoK1uYVRPV1HYCsBCbOn0RXz7oKWXWEGyjP'
    b'64BKuTpcUc18W5bTaplmFUGBcqAk28IECYLJT7n3t2HDJt7vTfelotFHtjHRmpiMOEQce01Y'
    b'iuWqf/jA4w8TIQDA+NHtaScSG7Ftu3+jFgSSWyqVBg8+y9dXueFnGjuW6Why3R7HdtqrEswt'
    b'/S6NH3o6PdvI/8/zBxKC2fJEt+o+AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
file_type_python = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAeRJ'
    b'REFUOI2lkjtolFEQhb97/10UxReaKFpFVEQNStKJYrRYEWwEwUaCYAyChUSiaCnYWIkgWERc'
    b'bSRYbGkjkYDamCUiiEbwEXBNZRIw+Nj/3pmx2Oyf3SRokYFhmOGcM2dgYInhFo4O5Tqv9fXn'
    b'jJOqsslMUjRWNMb7o7e7H/xXoONy6Xji/WnT8C3x7hIqYIqpUE1/H3hz59zLRnxugaJjvZkc'
    b'w+wHqhkZE3LGNmBxge19j7esyiVdTnRz4nQQi2CGmfViAqq0rZlaWX5f6CVNP7m9w0OZQOfV'
    b'UsHjn3gswQuoAQ5TpU5GhZ0t0+vA3SDJY6MHz7iO5w89gDfX77EkAzfYrpMxYU/r5PdarwBn'
    b'504w3Q02SxZiDJPOdBwTEAWLvzTG0qn2z10oYApqOxoEJI9RI1f/FMsXS2PgToDkCQBhBVGv'
    b'A6vnHKllAqY6hrMWU+HK4fIrfHK3BgTcbAUy+6og8hbAA4imxfrNuzZOb8i2NNWGjFEI1ZuZ'
    b'g9e3uov7LgxUfEJb6/KfyxqAisZ7AMQAJl8IocLMzDNX+DCx6Cfau6M9+GSgyUGMX1FZS5qe'
    b'd/tHHv3zE5H4EUezfZFBVLYCU/Phfv7AtQ8NU632EOILQhgnxAlMj6BSpjLydMHCpcZfS109'
    b'vxPI5PEAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
file_type_sketch = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAbJJ'
    b'REFUOI2lks9LVFEUxz/nvud7Tk0yvHyMSxeuhlqVG0FBgnTdQtD2gX+CGBQS/gcStHPj4jW0'
    b'qFVBQiC4cqcupKBCGAZTG38048x797SYZphh3pDUFy6cw+X7Pd/zvRf+E9Lv4uJj+FDNjdsA'
    b'Yn8dZx8cffirQD3iiY4WXrqDvrEWzNAjAGzlDcaBuHZl5ev+ojfHqxbHtIpyxBjCmuN7xlqL'
    b'ZGeR3P3muTWLtRbH9wzCWjlirEcgcNgygisiSGYaE0y1nZlgCslMIyIYwQ0ctroE6kXeGcgj'
    b'oAPjmHCmZ1cTzqDuOAgYyNdf8xbABah9405yCYkYhrKb6PfN1GBV4Wzf4KjFucndtsDhMRPD'
    b'Db5QtZnk8DNeLpVP/SfYMtgM1VKNifYKhVVKEjCJS3K+25yUNv18F9QlkYDJwiqlrhDDJXa8'
    b'kAWN0cZpr0DjFDRG/ZCFcImdrhBbyC0TOSM8r+yhnS5UobKHDuR5llsm6uSk/sSTF2wMhsz7'
    b'w83+6gfUjtgInvI4PZ00kRW24yIaF9GTFbavTex0V13noLrOQT+n8OcZ+0Dff+Jeq/4XB9fC'
    b'b4V3kWqIlz61AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
file_type_svg = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAmVJ'
    b'REFUOI21kk9Ik2Ecxz+vvuqgAs0xFTvMvYq45mjoexmjDuGmAw/+ufiCI4w8Rl6i8C56WEZ3'
    b'S/EmdNmkkzmQHBqeaoLgoj+KTdlKFDXdfH9dNhnYIYK+8IOH5/d8Pzy/7/PAf1QQ+JCv4N+a'
    b'bgKjgAvYjE+0SnyiVYDN/N5o/swf5a6rKpOnffVSV1UmagmZ79Pt5s6rdlMtIV3cA9wFU0kR'
    b'oHc4UMtYyE54qIGcSenXvTPlU+pUyZmoz4YaGAvZGQ7UAvQWTKVFgKNve6cPHLUW+rxWrl9V'
    b'LTeqKzAFbjVcsdz31xJ9/4Px19vsH50/BnYAlKLAngOVCpS9fNhYee9uDakfZ5ybQr21gum3'
    b'uwy9SO4LZIF94BHwpgBYfzfe6rTbKkj9zIII9hoL1ddUUBQyB1m+7P4CRaGuqozPe6f4nnxc'
    b'B1xK/hYmgNfrpa2tjUgkQk9PD7FYDNM06ezsJBqNYhgGS0tLLCwsXGRYAgiA2+0mEokQCARY'
    b'XV3F4XDQ1dWF3++nsbGRWCxGU1MTc3Nz6LpeAIhaWGmaRiqVor+/n5aWFjweD8FgkGw2SyKR'
    b'wDRNBgYG0DSNg4ODi+QvnnF+fp6NjQ22trbo6OggHo+j6zq6rpNIJMjlchiGQTKZJBQKXfpE'
    b'YrVaRdM0sdvtksvlxGazyeHhoRwfH4vT6ZTt7W0BZGpqSkZGRqQwekErHo9HTk5OZGZmRtLp'
    b'tKiqKouLi7K8vCzl5eWSTqdldnZWMpmM+Hw+AVaKAXeAtUAgIOFwWJqbmwUQwzBkcHBQAHG5'
    b'XDI5OSnd3d0CrAG3L83xL/oN/csBCkjCBOkAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
file_type_tex = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAVJJ'
    b'REFUOI3tUL1Kw2AUPbc1UD6kW211EAWddCn5ioUM2cRBHHwAdzfxZxCfwi6CuKiLk0+gdCgZ'
    b'Sr/bDkILIhTJ4CC4tCSWNLkurYhYn6Bnu5fD+QOmIACo1WprSqnM+BlFUVgul9vj2xgzT0QL'
    b'QRB89no9P5/Pr/b7/Q/XdbspAFBKHQ8GgwyAhyiKlGVZBz9dtNZvIrKplNoHABHZcF23+53A'
    b'87yi4zgtZn63bTtnjDkCsERETyJSEJF2qVS6Z+ZHEWlqrU8AJACQAgDHcVq/ql0Q0Y5t25e+'
    b'71cAFAAkw+Hwioi2q9Xq3Jg4888+s41G44yIugBuPc9bT6fTL3Ecn2az2WsAWwCERuQUMxdF'
    b'ZI+IbkSkQ0QdEVlJksSN43jZsqxcGIZ3o80OReRZa13509oYo5j5FQDq9bo2xpxPijmpwiKA'
    b'XWa2AUgQBBMFpgC+AH7skwsNnTA8AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
file_type_text = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAQtJ'
    b'REFUOI29kzFLxEAQhd/cJXHF5nrBMt1xvdUGzH+wEBHkCNh5cNgIcoWl2CloI2LhTxDikSnE'
    b'XgQh/8JCEBlyYxU5kmwwCL5qeex+++YtC/xRVC6yLJsS0R6AT8feDQB31trJsun9kIg2RWQ7'
    b'juPXptPMfAEgYubbPM/3kyQRAOh1iauqawB2wjA8L71fA6y1B1EUhSIyIqL12gilTq75sU8Y'
    b'NEEKxTsgh8teDTAb2622JGmaDlsBx1fz3YDIVP2vRfF2msRPVb9TiU2qJZBCXgIvqPkrvT6O'
    b'Lh9GABatAOOZMzhKNJ75hxKrz1goPmZja13AzgmcAFV99n3/npldn6nUqqredLmkVd8nZ1Rx'
    b'lHgPTwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
file_type_video = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAaxJ'
    b'REFUOI2lks9L1EEYhz/v+84ulrrpeugQeFWIoigPgnpQ7CTdAm8eupkHQYRu0Q/sD8hDJ7XE'
    b'm4IEnQRFCLoIVm4bCYXgJRR02bBVvzPv22FxZBH6LvS5vTPzPu/DzAD/GQKA4kBXWy6f/yDM'
    b'nfU0qer2fqnce2vl4x4DQFNry6CZvtXgZ1Kbg58x0/n8laZ+AHBVD2MYdwC4Vod0uwEC0p8A'
    b'wOfrummGH6kGhm0yFM7qCGDjIWa6mwZgRjeY7l0AqIbXCl05q931m59yjyZWleW4xkDtnWqY'
    b'vQAgkXGA7seNhkvJ5d6B/qtzS7+y3X0b8RzTA2YejYMA4PvOLtRsyhHdEeeeA4CUyuiZfIJy'
    b'cetPYXmx0U6qIj74haBhi0maIwAAMiLTAJqj6ulJw8bD4fXfX7/0MTNFM+IxFvZB9XENwCen'
    b'oyKZ22C8BAA7rtw4+lYA8/lDAYCZvQohfCbmlhqAc5lnRpRDSohoxDl3EFSnay7Rh/DUTOfT'
    b'AGb2xnv/Ig4GAFYyyWbfpzUDgIhMiQiSJBmOBpVKZU21+jXriWooHpbKq/We/2f+An+tqNHg'
    b'/S0XAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
file_type_word = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAYNJ'
    b'REFUOI2lkkFLlFEUhp/v3q+ZChxHFAxcJKhhSasKQVdCRssW/QATXKYbIRK3tWnrwoVEf6Bt'
    b'y0RCUUFcCEa2KJAgrIlJxGb87j1vm3ThmN+AZ3fO4X3Oe7kvXLCS04Ph199HC0X/OE8YMtv6'
    b'MNY5l55epKmfBv8gD5Be8gBzrlmr/wUBXJ9Yep7iuoPg6+LybZdEJAGR9oF+rpQ7G4Qx2s8T'
    b'gHfupQkShFwbUSCEJPY2Nin13DnreAeAAzATbyZvYSZWXw3S0ZKy8HSARMp9ggOQiZ1vhwzd'
    b'aOXj7gH3+krUjowQjDxGeuxgfafK+GgX8+92GbvfxdaXfSxEapXfBLd3vgMzsfapytDNMivb'
    b'Fa61FVjdrmBZgGYcyMSPX3V6nyyiaDx8toKiIbN/v5EDyOr1Gcm6CeKo8vmRQr0kk7PsQGYh'
    b'mIoAJLKaUJT0BynAGVG+enf2vXfJyHGfFMs41xBYAKpLU0nDxl9uz7xvPqANgCyGF47C2zxh'
    b'iGG/6Svn1V+T4rIPeIpoGQAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
toolitem_eraser = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAACxMAAAsTAQCanBgAAAJBSURBVDhPY6ALmGqrLVtvb88C5aIA'
    b'ZiiNFcy3t+eIcVBscsyLrBUXZAy1YmD6vunus2tQaTDAacBkC11dXX+dBfaFGaZ8khKsYmr8'
    b'PNLqnI6OXBz+Fhy8t3c8fvUEpI4RrBoJTPRQYef4w5dr7CGVpWSl8J+R4Q/D////Gf79/c34'
    b'79cPhj9//jO+PMXAeHjnJf+8o1cvorhg1apVbPzP7i029eSPEBL7y/z320eW39++sPz5+pn5'
    b'z+fPLH//s7G+vcTCcvvofVbGf/9PbHzw4joTVC/D0qVLVUVFRQ7//sfj8vYuMzsTjzD7r++/'
    b'2H9//8H2++cvDhYhXfYHe/+y3Tp0m/35py/f9714eRmkD+yFJUuW+BsY6C9TV1f///fX7/8X'
    b'Vy1meHZw43+LGEMGhr+vgCGlxXBr5T6GZw9fMjz59O3urfff4mbfvH8VqPUf2ICdO3e0iogI'
    b'l2poaP5nZmL+/+/fP4bXN68znJvU8l9WU4bx1fGL/99++cF47c2H+cvuv6p8+PHjR6C2/yC9'
    b'oDBglJWV1mBlZfV59+4ts6CQEBMbKxszr5g4039FdeZHmzcyPXj++sP1tx+ruy/dafv48+dX'
    b'kEYYAAfikSNHL3Bz8zxiYWEx//PnDy8rGxvjzZs3mO4/esRwbt3q7Rfffcycff3hJqDS3yD1'
    b'yAAWC/8uAsGvX7+2/fv3V1dWVlb++fNnDLt27ZkyYevuwivvPt8BqYEoxQ9AYcIbExNV6OXl'
    b'Hglk80DFSAasUDzoAQMDAJsz8RPQzITPAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
toolitem_mouse = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAC/SURBVDhPnZM/DgFBGEcXJ5BQSxQq'
    b'So1olTqt3iE0NDqVSCSO4AqKPYBG5QBKd+D9zEz8m9n94iUv35fs5mV3spt90cGKW/9ji0s0'
    b'R6p+vnPABZoiscAZzZFYQJgjqYAwRYoCojRSFhCFEUtAJCOWQAP3OMYmDjGJPqRA3U8x9/OH'
    b'2BO0cI07DNePOHLrJzU/AwPU/7DCG/bwglecYo5mdFgbtz6ZYd+tL5IfiGeCbdR9J9Sr3NGM'
    b'zqDr1hhZ9gDH1hx6UZD9hwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
toolitem_palette = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAL6SURBVDhPpVNdSFNhGH7OOTvbmZub'
    b'5ubStmo5NVNRrBBnYCTVRRchSPRzkRVdFAVFUXQT3URdFRERFF0YiURS6k1gll1EZmVFplbO'
    b'+bOl4aZuO2c/52znnL7VhIrueuDhe3l/nvfl5f3wv6Ay70+0Hy8vyjYaD+UUOncazJZ1jFYH'
    b'VQVSYkyIBPwv5/3j7c3XRlpJKvH+wpIA1X1242VnTcMZc14upJAHIh8iQQmWKjekiISUEIPC'
    b'5sI39PrtzNTY7j3Xh8fThczP4nN1V6q2Np1SI6PQMAtwVlLIzs8HZTbDVt0Gk9MMf58XsjAJ'
    b'W0lNIU1ze+sdyc6uweACffOAq6yopu5EbPYFZCUGjvEA31rBCa1kkndE3odEsBu0wQClYi14'
    b'eRqOYrtlpdN5izSnmT1u2zFXlbPB9lWPPC+DqCkXIqNiMexAPFyA4MdyRDxO8C49+i2diNh1'
    b'sA2FYSwoWV1pCvXRskJlQRGA7kcQ+x6C+TSJcHwtxFQBNDoKWgPAZtFIhicQVYIQ5j5AQ5Zr'
    b'MAJGltrONG2wbVtTbHFLeRxkqwmJWgeZiwGtYeAbDwhvP/ifiJE4t2aZw1w6vwGqcgQJLYdc'
    b'eQaezzMD9FQwMRDwB4FKO1KN68Bk6UCzDPhwDPd7vEcP3/jYcrfXe5CPCHild2O3pwSnos1Q'
    b'VCm9AmjOd3gezy6K+0sdxsakJGO5Ve/atKXMTTEccgzUEMkK1rvMlM5khcJPYCFWgejcV7CO'
    b'FKSkHFq6A5ZQmzaKrLqCBxcbx+wV6/Fl8Mtogg89y1tVtG+FY3OOvCjDaOiFrIr4NsPjauu7'
    b'Wk26iCCZIcYD4vf0q8T9KK+vLqNZfZkiTWPwwi4IPqCkJQuW6i6Mff7ef+eZf5hOJ/8FVaPT'
    b'gNGy5PomIC2OQJEWoKamoZAWLOfF6Bvv/L3nE6dJbvyPv5AB13aypqOiyr5DVTIeSiWLlRAN'
    b'p4Thkdmnt3t8lwbG+PckIv1LIO3LJ7Rm7N+RXn2AMES4JP8/AH4A2Fkz3oraNbQAAAAASUVO'
    b'RK5CYII=')

#----------------------------------------------------------------------
toolitem_pencil = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIASURBVDhPYyAVnA/XV7gcaeQO5TIw'
    b'QWmiQKG3o/5Hab2Tgs4Rm48F6geCxJjBMkSAnTG2ijd4pI/e+MUsIvnvF7OUnlmQF8urK0QZ'
    b'cCXNRU7L1Xa/sPgHqauvWRkuvfnMIP7zC/OPfwxfCRpwBqhZydHqAJ/8O0Xu97cZ2H+8Ybj/'
    b'R4rhwKXrp1t3HijAGwZnYl3k1BwtD/BKv1b8ePsKA/NfZgYtCQkGkbund2w6djr550+GR4xQ'
    b'tRgApFnVw+IAn/QbxQ93rzL8/cPM8PWvCMOZfQ+WRa85U/GDgeE5UNkfrAacibWWU3V3PMAn'
    b'9Urx/Z1rQM1MDN/+iTKc3v9waezaM+XfGRheApX9AanFMACs2c1+P6/Ea6V3t68x/PsL1Pxf'
    b'jOHMQUzNIIBiAEizkqv9fgHxl0pvoZq//xdnOHP4EVbNIAA3AKLZcT+/6DOlN7euMfz/x8Tw'
    b'g0ECqPnxkth1pyuwaQYBcCyEhoYy8+lobuEW+a/05vYdhv9AP/8A24xfMwiADcgI03Lm9/HR'
    b'vXrsBjCwxRl+MMkwnDnyhKBmEAAZwCgpKhj0+9cnBhFfd+YnT/78Pnv00eKQdaex+hkdMKmo'
    b'qLC9ePEs4Punpz9v3L1//CQrT2XwmhPFQLlXQIxXMxg0V0fJuzsY9MnLizsAuTJAzAnEOBMY'
    b'KmBgAABB3eRdALVpagAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
toolitem_thick = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAA2SURBVDhPY+yfs/Y/AwWA8T8QQNlk'
    b'AUY5y+gBdgHFYTDqBQYmKE02oDgMKHfBgIfBQBvAwAAA74IfT9z/D/wAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
toolitem_brush = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAACxMAAAsTAQCanBgAAAJdSURBVDhPY2QgA3QX63H7+MbXvHv9'
    b'TIoZKkY02NIXpGRl57xXWJT//6vnjy6Q5IIN/SHqRhbG+7l5uSUf3Lh64syuM3ZQKcJgc4uq'
    b'9LOD2Q8/Xyj5f3dr2O35WaISUCnCYFuuCvuT7X5nvhwP+39nvfvVBYVC0lAp7GBVKAPzzDQG'
    b'VhC7vp6B6eYi7cXvt2j+vzxHYe/sZD4hsCIowAgDY2Nj1nnZvKskRNn1Xr790s/F+cdNgOOT'
    b'7+0HX7ofH3lcGbaa4S9UKRigGFBfX89kpKu+VF/mW4TAq6kMTCx/Gf79+8Vw6+H3mWbZDzOg'
    b'ylAAE5QG22yop7FQQ0Mt4iev0f9HnLEMP3/9ZvjH8Ifh+7ffx6HKMAA4HcTH23P4WZgttHF2'
    b'j/z+4yfju3fvGb8yCP9/842Xkf//RQZWNkZtYb2PUw8eZPgP1oUEmMuiPWQMVLV2a6hIur5+'
    b'8YyRnU/0//sPHxjfv3/P+PmP4P8XH7kZPz+7uimt7stGqB4UwCSnrDpDS0fd6BcDO8O3T+8Z'
    b'7p4/zMjw////r1+/Mbx+/Zrx7APuaV7Vz1OAajFsBwFme0P1Wz9//o3+/+8P25ePbxh+f/vK'
    b'8OXje8Z/rNz/7z98PLm9oycXqA6rZhBgKp+w+Myjh/e9H9668RkUJBw8AgxcwBTw8PLxmRxc'
    b'vIVANSxAzAbEoHSBEe1wgdrUIEcpaZn1ErKy/GdPnbzRNWd98a+/f0Gx9A2I3wHxSyB+A8S/'
    b'gRgO4Lnx0LnrD3SVxda8e/NebdLSrYu+/vj5ASj8BIjvQ2kQ/x8QIwEGBgDKB/ADIHGkgQAA'
    b'AABJRU5ErkJggg==')

#----------------------------------------------------------------------
splash = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAAABmJLR0QA/wD/AP+gvaeTAAAA'
    b'CXBIWXMAAAsSAAALEgHS3X78AAAAB3RJTUUH0wwFFREJmrgjPQAADuBJREFUeJztnT1w20YW'
    b'gDc3qY5dIKZmI3jGrJ0RXKmOqO58paUucamoi1066WyXznWSyzidydSuBE9UyzOmGtYhkY5X'
    b'X7EJQ5PYtz8ApOTe91U2RRAgsN/u27c//OSnH48NgFb+cdsXAHCbIACoBgFANQgAqkEAUA0C'
    b'gGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0CgGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0C'
    b'gGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0CgGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0C'
    b'gGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0CgGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0C'
    b'gGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0CgGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0C'
    b'gGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0CgGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0C'
    b'gGoQAFSDAKAaBADVIACoBgFANQgAqkEAUA0CgGoQAFSDAKAaBADVIACoBgFANQgAqvn0ti8A'
    b'oCuqajmdzo0x0+v5olqenuxvv6cTAeyJL97NynL204/HXZwCYIPp9bwsZ4tquSr36+xkvdqj'
    b'2hSgqpblu9lFOVs//XhyNToYtngWgFrejK/Kcub6627er329BQFqy/2K8fg9AsANIJR+gUYC'
    b'VNVyPHn/ZnwlvGdRLafX83y33j+AVphe11S+69zfG9S+nihASNFfcXb+y/dPD6I+/9mLt9sv'
    b'3sn73sbk/NXlolpuvLiT9Y4e3ou6gBW1AeWff/1t+WHtr/f3BkUxuIEThdwK+US2X7j+ui0i'
    b'ed7PHOFyFOPJ1Ye6r1PbE12nLGcX72bbrx8/vCdc2HT6q/yx2U57fYCqWj5+8vN2OXMxnc6r'
    b'ahl+W8eT+mDujiOMW1GWs1onj49qSn9VLc9eXRpfyYvi2KGZ9bnFEx2Ooku/rbNsN7H2Dat7'
    b'vpP1imJQFIPkdruqlmfnl9uv574naBxVmFfLWtk++gTHd4kWoKqWXz16HXvUePI+vA4ej99v'
    b'v7iT9UKq//ADy3eztKjRheshlWX7J4oqmlb18GtYVMs346s346s87x8ffZGgwXhS8wSNMcdH'
    b'X/gOvKr1876vXZW/ndAsxw2E2bo/6hBLYLBkjHFVUd7QorbmMMZ8881+7fsvylngJQXierq1'
    b'DXoXJ6plPLn66tHrNAOn0/m3jyfPXrytglt7S+3j3sl6XpfS6j5vB0CIHeIEGE/eh0c+W8cG'
    b'OfDG8bbRwV3hKFfw42rHW4xGLEKt3G71H1KMLFW1/PbJpDYUiaIsZ4+f/BzugOtBj0bSEzTu'
    b'6t97oPcO5/nnrj9FCFBVy/CK/OPT94tiUFX/9b5zej2vLZdyCFhVS1fw4+pytVv6jbuNbrf0'
    b'm4DSYLFtdVtfc1Etwx2orcWNMYUjDyMfGBL6fvD1gIUqI6IPUMY05XnePzwYxqYUzs5/qX39'
    b'0H0LhB65K/gxbYclwkPyts6xhCR/YrMUIVgHfnj5QH6bqxYvioFcEoQDvdcmey5/QoQA3o72'
    b'6nxyxsqFKyyxSQnXIa4nfXqyL3jfsGLeyXrrI4uuHHPrJ/LmwUw3pd+yqJbnry7lZMZFOat9'
    b'3Zu2crUbcuhrAu6wfNMiBLgOEOD0ZD85Ee5KHSSUfpvFc51oej3f+GvtTdzJet4KT6aqlrt5'
    b'f9fUP4Dr6WYm3tJw9tSzF29DSv/6HQi01IaywhtcEay33+Kq/g9HQ29N6m3M5dArQgDvbW1S'
    b'+oUORm0dUJYzV9qnKAbyaEu+219/g51EVXPesGhbIHN3QlzZ5IQE/zrnry7leOBwNKxJDJyY'
    b'6fX87PwX17GB+VBXBOvv/rq6DQHFSa6Xd7KerFBrk+HsnU0+3FX91/Yizl9dumwROr4uXI/N'
    b'22lrQmxzF8L0ei5kKeTQNN/tf//04NmLtxt1QfhQgKv6N7476ar+Q4Y7tsezN0/tu5+tCdBw'
    b'to+rFd7o/k6v58+fO5v4naz33dMvo86blndqiKu5ix3h2sBlsjHm+OheSO/59GT/mfndgfq2'
    b'wo3rCfq7v47qP2S4w58A9V1/hAA7Wa+LrpVx1wHr3V/v7CNb+mNLbULeqTmu6t873ikgVMCH'
    b'o2H4xKHjh/d2st7o4G7UnRQiWDmoEx59iHveBGibLcBu3l+UTgHeTK7Su7+uDMAfseN4cjUe'
    b'S2Nwed4/PdmPLf1Cp61JKCIj9nbSrXMGcsUgaiJgljRxUIhgPd1f36MX8I5mhjzECAEOR0Oh'
    b'xbETDBNacGF6VrE3kDtnv7/N1+t1IRSa1b+n1/NqsXl5XfR2mnR/haLgmp/XLi6lt9s0e6nZ'
    b'Ti/f7buqfxNWF3gHpoT09IoIAfLdvhwFJUx7Nu65D3nef/birXcs83A0TJvqLMQMdiqY60A5'
    b'xyojVP+Nur/u4Ke7nswKYZJL9llvNS96o/b8z8sHruo/sC7wDky13AIYY0aju8Lckul0HrsA'
    b'UiiF3qJvZ/knl5vkIaqQesVFcqgg48qFe0eRWsFVjo1jXYdFmFMceNnJM0DXiZsMNzoYuhYX'
    b'W87OL6MG/5NLYVEMvnv6ZRc1sUyT7oFw0ibdX+PIhXeayFrhTUTGEnjZ3pITWE9F7wskTLCx'
    b'PH/+NvCj0kqhzfQndHnXcdXEXrqI/k2z7q9xjFE2lCoQIfeaRuBkb/8AcBctgDEm3/WMhy+q'
    b'ZeDM59hSuJP1jo/u/fDyQcMUTXL1bxoIkJwoDPnk2tezz26i+m93Xm34ZG95ADhk6ZklZWc4'
    b'myoW3hA4Bz02/llUS2FidzjJ1X/444k6aUOfneOv3bcAtzXZ2xt3hbd+KSPBNlUs9G9MwHZA'
    b'QgpMIC3RtIHrsdVGn+uhpGthdcOT/k23zGjSkLoIDAW94oVPY0mcClEUg3zSF5q/i3Imf5mL'
    b'cpZw3uTRhhWCeA37FWknvZlIvQvC14es2qL7e4Pqt/r18iYmFJQFiOr9p88FOj764tvHE9df'
    b'5Z0gpIlTxUD+eg0bASH33F3OREgUdrdrWNROHAm4vpRdC2UcMZjQPwyM2VqMf0yT3aHtuJjw'
    b'BqGGEIr46cm+XBPYRsB7efXHuu9ddxGzMNTdsPsr0/qyz48+3H0nDw+GwljhRTmrfT08FGyy'
    b'AnibRtuju/ZbtAgDdXI+xDu8ldz3cp2300DcNdRtWrLOWdTa3o1iHWE6urwUyTloHdwSyk8/'
    b'NlHR4e8DuC40pBGUE01pfa+qWrouqbtAXJil0ySnFEJZzmK3MwlEuJNpNVf48KLchhfFIHYZ'
    b'0y38PsBFOat9fb1AZFnPM+0ivisshGTdrX2RBr8arzhb4eo4nb26TJsmKCPdSbEcN58HVS2W'
    b'h6Ph6tE3H+1u1AKErBLeQO7+rv9XnnaREAUJ6+666ywK19mida5133bhqPfw8eTq60evI3b+'
    b'cdxJuU1r3v01f8zutpV9Kw8uvQVwLcmVEQrE9hSoohi46gzvSogNhKbz/t5ACFQ2dqWN2vBC'
    b'mundqnXF3sDVWr4ZX7l+HMV8vGvi4yc/h0wuFO6k3KYJWaNbHAlJFGA8kSYMW2qHo4Vu6HaB'
    b'EASITXEIVyuP6K0T2+AK3d928z9Z1hPSx2U5+3r6ejS6W+z9aV1ZzjbWEC+q5bMXb49/8yye'
    b'lCaKu9s0qQK61ZGQaAFCVqhY7mxlo4Tqv/YuyBVDeDdA6LRFEfWobrj7Ky9XWlTLs/PLkCkq'
    b'Z+eXH6ZzoaGLGkdfkabNDRAhwHhydeH4GZhathtTKSHouAtCxVYtliYwc9xSQjDqUSX3FNPI'
    b'd/uHo2ErcxNs+qh2tFGI4+XaIXnJvPBpq+jU7rCUto+TR4CynNnTxNag24GdUCN2PXNdGIgN'
    b'J/ZRiaO/naxTOXp478P01+bjX8LWMhflzHWUUDtI2sTUKV8/ei10O+VRKRdOAf7177OEj1ux'
    b'PatbSAh2ugVDWys2oh6VcNJObT892W+4L6KwuYacwRO+1EU5c/0pvDEUMgqWtJV6zjRok2a6'
    b'dj8ZKSGYdK7AuZmtRAWxC8GEk3Zqe5b1miyUOxwNf3j5IDb6N2LhC098y7S1AmYDZwsgz/MR'
    b'qG1A5YSg8Gm1N91Wom1NHQkh9ua2bns4dj/Gce7ZSGaDw9HQuxeQvFGA60+ufVd3835UKqyt'
    b'FTAbOAVIS1O49mZb6WvL7ioN4t1s1b7BVjB2L42o6xEK4nYocifvb6yiSgtX1k9qr99+csL1'
    b'JzM6GI4OhnZHBtnGwB/2W/8FMRttB/6o3qJaFsVgdW/T/K+qpSzzdsoxkE9cexFPr+fCbOda'
    b'hPCxLGc3sEBpm9WuPjezQnx1UtN4r8h22c5AxD6O6fU8++yfN3YPNxhPruQcbvLGzK21APLe'
    b'q7dS+o39FjdeEP9SRd+SZb2iaFR2b/dLtbIFUC1SGjTPpTVf6wTuvQqQhncJWPInSwJkWc8Y'
    b'v3lpvwcDEIhr/dOqa9EkvpAEuL8nrU6M3T4bII31X4HP8/6d/PMWC170XKA8798vBuvTqgA6'
    b'5cN0brNVXWQynFkgy2o8mHIP/5d4WgC7+ua2cjgAXeMRIG3ncYC/Cx0uigf464MAoBoEANUg'
    b'AKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUgAKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUg'
    b'AKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUgAKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUg'
    b'AKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUgAKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUg'
    b'AKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUgAKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUg'
    b'AKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUgAKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUg'
    b'AKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUgAKgGAUA1CACqQQBQDQKAahAAVIMAoBoEANUg'
    b'AKgGAUA1CACqQQBQzf8AeOtdXdgtYeIAAAAASUVORK5CYII=')